/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RncRouteImport } from './routes/rnc'
import { Route as InspecaoRouteImport } from './routes/inspecao'
import { Route as IdfRouteImport } from './routes/idf'
import { Route as AuditoriaRouteImport } from './routes/auditoria'
import { Route as AlertaRouteImport } from './routes/alerta'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const RncRoute = RncRouteImport.update({
  id: '/rnc',
  path: '/rnc',
  getParentRoute: () => rootRouteImport,
} as any)
const InspecaoRoute = InspecaoRouteImport.update({
  id: '/inspecao',
  path: '/inspecao',
  getParentRoute: () => rootRouteImport,
} as any)
const IdfRoute = IdfRouteImport.update({
  id: '/idf',
  path: '/idf',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditoriaRoute = AuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertaRoute = AlertaRouteImport.update({
  id: '/alerta',
  path: '/alerta',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alerta': typeof AlertaRoute
  '/auditoria': typeof AuditoriaRoute
  '/idf': typeof IdfRoute
  '/inspecao': typeof InspecaoRoute
  '/rnc': typeof RncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alerta': typeof AlertaRoute
  '/auditoria': typeof AuditoriaRoute
  '/idf': typeof IdfRoute
  '/inspecao': typeof InspecaoRoute
  '/rnc': typeof RncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alerta': typeof AlertaRoute
  '/auditoria': typeof AuditoriaRoute
  '/idf': typeof IdfRoute
  '/inspecao': typeof InspecaoRoute
  '/rnc': typeof RncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/alerta'
    | '/auditoria'
    | '/idf'
    | '/inspecao'
    | '/rnc'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/alerta' | '/auditoria' | '/idf' | '/inspecao' | '/rnc'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/alerta'
    | '/auditoria'
    | '/idf'
    | '/inspecao'
    | '/rnc'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AlertaRoute: typeof AlertaRoute
  AuditoriaRoute: typeof AuditoriaRoute
  IdfRoute: typeof IdfRoute
  InspecaoRoute: typeof InspecaoRoute
  RncRoute: typeof RncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rnc': {
      id: '/rnc'
      path: '/rnc'
      fullPath: '/rnc'
      preLoaderRoute: typeof RncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspecao': {
      id: '/inspecao'
      path: '/inspecao'
      fullPath: '/inspecao'
      preLoaderRoute: typeof InspecaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/idf': {
      id: '/idf'
      path: '/idf'
      fullPath: '/idf'
      preLoaderRoute: typeof IdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditoria': {
      id: '/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerta': {
      id: '/alerta'
      path: '/alerta'
      fullPath: '/alerta'
      preLoaderRoute: typeof AlertaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AlertaRoute: AlertaRoute,
  AuditoriaRoute: AuditoriaRoute,
  IdfRoute: IdfRoute,
  InspecaoRoute: InspecaoRoute,
  RncRoute: RncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
